### ISSUE TITLE
NVAPI_ERROR

### ISSUE THREAD

**Issue by QQ2017** [conchyliculture/NvapiFans#18]
C:\Users\admin\Desktop\NvapiFans-master\win\Release>NvapiFansCli.exe
Error calling NvAPI_I2CReadEx: NVAPI_ERROR
Error calling NvAPI_I2CReadEx: NVAPI_ERROR
Error reading bytes from I2C device during identification.
Failed to detect all GPU I2C devices

**Comment by conchyliculture** [comment]
Which GPU are you using? (manufacturer & model)

It looks like the I2C devices & addresses are different than mine.
It's way easier to figure theses out with a Linux OS, so if you can boot under a debian based linux and do as root:
```
apt install i2c-tools nvidia-smi
modprobe i2c-dev
```
and list here the output of:

```
i2cdetect -l
```
and
```
for bus in $(i2cdetect -l | grep NVIDIA | cut -d$'\t' -f 1 | cut -d "-" -f 2); do echo "i2c bus: $bus"; i2cdetect -y $bus ; done
```

**Comment by QQ2017** [comment]
OS：Windows 10
GPU：NVIDIA GeForce GTX 750 Ti

**Comment by conchyliculture** [comment]
Can you also provide the manufacturer & model of the graphic card itself (not just the chip on it).
As an example, all my tests were run on  a `ASUS ROG Strix 2070 Super`

**Comment by QQ2017** [comment]
Zotac GTX 750 Ti ( 1 GB )

**Comment by conchyliculture** [comment]
It doesn't look like this board has any separate header for extra fans, which explains why detection fails.

I'll add some extra warning

**Comment by conchyliculture** [comment]
To be verbose, this means you can use any normal too using the nvidia driver to control the GPU fan
